### ISSUE TITLE
Adding external libraries to the compilation workflow

### ISSUE THREAD

**Issue by loumalouomega** [oberbichler/kratos-dev#2]
How can we consider external libraries in the compilation workflow?

**Comment by philbucher** [comment]
basically the docker-image has to be updated

can you post here how to include mmg?

**Comment by loumalouomega** [comment]
Basically what is used in the nigthly (former).

~~~sh
# mmg library
wget https://drive.google.com/uc\?export\=download\&id\=1RM-SpxbynS6_zby8TjaJvIEC9NA-IxRZ -O mmg.zip
unzip mmg.zip
~~~

**Comment by oberbichler** [comment]
I just added `mmg` (5.4.1 from the homepage) via a simple `ADD`. It should be available now.

Using `wget` would also be possible. Is there a modified version on Google-Drive?

**Comment by loumalouomega** [comment]
I can update the version of google drive, the main difference is that the drive version is compiled

**Comment by loumalouomega** [comment]
In fact I just check, you are adding only the binaries, but the libs are necessaries

**Comment by oberbichler** [comment]
I am installing it now from source:

```
/usr/local/include/mmg/mmgs/libmmgtypes.h 
/usr/local/include/mmg/mmgs/libmmgs.h     
/usr/local/include/mmg/mmgs/libmmgsf.h    
/usr/local/include/mmg/mmgs/libmmgtypesf.h
/usr/local/include/mmg/mmg3d/libmmgtypes.h
/usr/local/include/mmg/mmg3d/libmmg3d.h
/usr/local/include/mmg/mmg3d/libmmgtypesf.h
/usr/local/include/mmg/mmg3d/libmmg3df.h
/usr/local/include/mmg/mmg2d/libmmg2d.h
/usr/local/include/mmg/mmg2d/libmmg2df.h
/usr/local/include/mmg/mmg2d/libmmgtypes.h
/usr/local/include/mmg/mmg2d/libmmgtypesf.h
/usr/local/include/mmg/libmmg.h
/usr/local/include/mmg/libmmgf.h
/usr/local/lib/libmmg3d.a
/usr/local/lib/libmmg2d.a
/usr/local/lib/libmmg.a
/usr/local/lib/libmmgs.a
/usr/local/bin/mmg3d_O3
/usr/local/bin/mmgs_O3
/usr/local/bin/mmg2d_O3
```
Let me know if there is still something missing.

**Comment by loumalouomega** [comment]
Well, we need to update the configure.sh

**Comment by oberbichler** [comment]
Why?

**Comment by philbucher** [comment]
to enable the usage of MMG
@loumalouomega can you do that please?

**Comment by loumalouomega** [comment]
I am lost, I thought this was already applied

**Comment by oberbichler** [comment]
MMG is now accessable via `PATH`. I don't know what additional steps are neccessary to use these tools inside Kratos.

**Comment by philbucher** [comment]
@loumalouomega from what I understand MMG is now available inside the Docker Image

However in order to use it I think the configure.sh of Kratos has to be changed, can you please take a look?

**Comment by loumalouomega** [comment]
> 
> 
> @loumalouomega from what I understand MMG is now available inside the Docker Image
> 
> However in order to use it I think the configure.sh of Kratos has to be changed, can you please take a look?

Do you mean the one in the repository?, sure

**Comment by philbucher** [comment]
this one: https://github.com/KratosMultiphysics/Kratos/blob/master/.github/workflows/configure.sh

**Comment by loumalouomega** [comment]
Where are the libraries located inside the docker?

**Comment by philbucher** [comment]
> I am installing it now from source:
> 
> ```
> /usr/local/include/mmg/mmgs/libmmgtypes.h 
> /usr/local/include/mmg/mmgs/libmmgs.h     
> /usr/local/include/mmg/mmgs/libmmgsf.h    
> /usr/local/include/mmg/mmgs/libmmgtypesf.h
> /usr/local/include/mmg/mmg3d/libmmgtypes.h
> /usr/local/include/mmg/mmg3d/libmmg3d.h
> /usr/local/include/mmg/mmg3d/libmmgtypesf.h
> /usr/local/include/mmg/mmg3d/libmmg3df.h
> /usr/local/include/mmg/mmg2d/libmmg2d.h
> /usr/local/include/mmg/mmg2d/libmmg2df.h
> /usr/local/include/mmg/mmg2d/libmmgtypes.h
> /usr/local/include/mmg/mmg2d/libmmgtypesf.h
> /usr/local/include/mmg/libmmg.h
> /usr/local/include/mmg/libmmgf.h
> /usr/local/lib/libmmg3d.a
> /usr/local/lib/libmmg2d.a
> /usr/local/lib/libmmg.a
> /usr/local/lib/libmmgs.a
> /usr/local/bin/mmg3d_O3
> /usr/local/bin/mmgs_O3
> /usr/local/bin/mmg2d_O3
> ```
> 
> Let me know if there is still something missing.

I guess here

**Comment by loumalouomega** [comment]
Let's see if works https://github.com/KratosMultiphysics/Kratos/pull/6345/

**Comment by oberbichler** [comment]
cleanup?

**Comment by loumalouomega** [comment]
Yes, do I reopen?

**Comment by oberbichler** [comment]
no. maybe I should also do a cleanup :D all the container stuff is hosted on the Kratos team? so we do not need this repo anymore right?

**Comment by loumalouomega** [comment]
Certantly, I don't know

**Comment by philbucher** [comment]
Yep this is all inside of Kratos for years already

**Comment by oberbichler** [comment]
2019... how time flies...
